CREATE OR REPLACE FUNCTION ds_demo.processa_comprovantegeral("pPAR_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
  pPAR_CODIGO ALIAS FOR $1;  
  
  vCODIGOCOMPROVANTE NUMERIC;
  vRETORNO NUMERIC;
  vQUANTIDADE NUMERIC;
  
  cCOMPROVANTEGERAL CURSOR FOR
  SELECT ID
  FROM ds_demo.COMPROVANTE  
  WHERE  PARCEIRO_ID= pPAR_CODIGO
    AND PROCESSADO= FALSE;  

BEGIN
 
  vRETORNO:= 0;
  
  OPEN cCOMPROVANTEGERAL;
  LOOP
  FETCH cCOMPROVANTEGERAL INTO vCODIGOCOMPROVANTE  ;
  EXIT WHEN NOT FOUND;
   SELECT ds_demo.PROCESSA_COMPROVANTE(CAST(vCODIGOCOMPROVANTE AS int8)) INTO vQUANTIDADE;
   vRETORNO:= vRETORNO + vQUANTIDADE; 
  END LOOP;
  CLOSE cCOMPROVANTEGERAL;
  RETURN COALESCE(vRETORNO ,0);

END;
$function$
;
