CREATE OR REPLACE FUNCTION ${schema}.processa_comprovantegeral("pPAR_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
  pPAR_CODIGO ALIAS FOR $1;  
  
  vCODIGOCOMPROVANTE NUMERIC;
  vRETORNO NUMERIC;
  vQUANTIDADE NUMERIC;
  
  cCOMPROVANTE CURSOR FOR
  SELECT ID
  FROM ${schema}.COMPROVANTE  
  WHERE  PARCEIRO_ID= pPAR_CODIGO
    AND PROCESSADO= FALSE;  

BEGIN
 
  vRETORNO:= 0;
  
  OPEN cCOMPROVANTE;
  LOOP
  FETCH cCOMPROVANTE INTO vCODIGOCOMPROVANTE  ;
  EXIT WHEN NOT FOUND;
   SELECT ${schema}.PROCESSA_COMPROVANTEBB(CAST(vCODIGOCOMPROVANTE AS int8)) INTO vQUANTIDADE;
   IF vQUANTIDADE = 1 THEN
   UPDATE ${schema}.COMPROVANTE SET PROCESSADO = TRUE WHERE ID = vCODIGOCOMPROVANTE;
   END IF;
   vRETORNO:= vRETORNO + vQUANTIDADE; 
  END LOOP;
  CLOSE cCOMPROVANTE;
  RETURN COALESCE(vRETORNO ,0);

END;
$function$
;