CREATE OR REPLACE FUNCTION ${schema}.processa_conta("pINT_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
declare
pNOT_CODIGO ALIAS for $1;
vRETORNO NUMERIC;

vCONTAID NUMERIC;
vCNPJ TEXT;
vPARCEIROID NUMERIC;
BEGIN
vRETORNO := 0;	
SELECT CNPJ INTO vCNPJ ,PARCEIRO_ID INTO vPARCEIROID FROM ${schema}.INTELIGENT where id=pNOT_CODIGO	
SELECT ID INTO vCONTAID FROM ${schema}.CONTA WHERE CON_CONTA = vCNPJ AND PACEIRO_ID = vPARCEIROID;
IF(vCONTAID != null) THEN
update ${schema}.INTELIGENT SET ASSOCIADO = TRUE, CONTA_ID = vCONTAID WHERE ID = pNOT_CODIGO;
vRETORNO := 1;
END IF;
return vRETORNO;
END;
$function$
;