CREATE OR REPLACE FUNCTION ${schema}.processa_extrato("pEXT_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
  pEXT_CODIGO ALIAS FOR $1;  
  
  vRETORNO NUMERIC;
  vCODIGEXTRATO NUMERIC;
  vDATAEXTRATO DATE;  
  vHISTORICO VARCHAR(150);
  vNUMERODOCUMENTO VARCHAR(35);
  vNUMEROCONTROLE VARCHAR(35);
  vDESCRICAO VARCHAR(30);
  vDEBITO NUMERIC;
  vCREDITO NUMERIC;
  vASSOCIADO BOOLEAN;
  vAGENCIABANCARIAID NUMERIC;
  vPARCEIROID NUMERIC;
  vTIPOINTELIGENTE VARCHAR(1);
   
  cEXTRATOBANCARIO CURSOR FOR
  SELECT  DISTINCT EXTRATO.ID, EXT_DATALANCAMENTO, EXT_HISTORICO, EXT_NUMERODOCUMENTO, EXT_NUMEROCONTROLE, EXT_DESCRICAO, EXT_DEBITO, EXT_CREDITO, 
  EXTRATO.AGENCIABANCARIA_ID, EXTRATO.PARCEIRO_ID
  FROM ${schema}.EXTRATO
   LEFT OUTER JOIN ${schema}.INTELIGENT ON INTELIGENT.EXTRATO_ID=EXTRATO.ID
  WHERE EXTRATO.ID= pEXT_CODIGO
    AND INTELIGENT.EXTRATO_ID is null
  ORDER BY ID ;  

BEGIN 
  vRETORNO:= 0;  
   OPEN cEXTRATOBANCARIO;
  LOOP
  FETCH cEXTRATOBANCARIO INTO vCODIGEXTRATO, vDATAEXTRATO, vHISTORICO, vNUMERODOCUMENTO, vNUMEROCONTROLE, vDESCRICAO, vDEBITO, vCREDITO,
  vAGENCIABANCARIAID, vPARCEIROID;
  EXIT WHEN NOT FOUND;
   vASSOCIADO      := FALSE; 
   vTIPOINTELIGENTE := 'x';
   INSERT INTO ${schema}.INTELIGENT ( extrato_id, parceiro_id, agenciabancaria_id, datalancamento,
                                    historico, NUMERODOCUMENTO, NUMEROCONTROLE, DEBITO, CREDITO, 
                                     periodo, associado, tipo_inteligent
                                  )
                           VALUES ( vCODIGEXTRATO, vPARCEIROID, vAGENCIABANCARIAID, vDATAEXTRATO,
                                    vHISTORICO, vNUMERODOCUMENTO, vNUMEROCONTROLE, vDEBITO, vCREDITO, 
                                    concat(extract(month from vDATAEXTRATO),extract(year from vDATAEXTRATO)), vASSOCIADO, vTIPOINTELIGENTE
                                  );
  vRETORNO:= vRETORNO + 1;
  END LOOP;
  CLOSE cEXTRATOBANCARIO;  
  
  UPDATE ${schema}.EXTRATO SET processado = true where id = pEXT_CODIGO;
          
  RETURN COALESCE(vRETORNO ,0);

END;
$function$
;