CREATE OR REPLACE FUNCTION ds_demo.processa_notafiscalgeral("pPAR_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
declare
  pPAR_CODIGO ALIAS for $1;
  vRETORNO NUMERIC;
  vQUANTIDADE NUMERIC;
  REC RECORD;

BEGIN 
  vRETORNO:= 0;  
  FOR REC IN
    SELECT id  FROM ds_demo.NOTAFISCAL  WHERE  TNO_CODIGO=0
    AND PARCEIRO_ID = CAST(pPAR_CODIGO AS int8) AND PROCESSADO = FALSE  
  LOOP
   SELECT ds_demo.processa_notafiscal(REC.id) INTO vQUANTIDADE;
   vRETORNO:= vRETORNO + vQUANTIDADE; 
  END LOOP;
  RETURN COALESCE(vRETORNO ,0);
END;
$function$
;
