CREATE OR REPLACE FUNCTION  ${schema}.processa_notafiscal("pNOT_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
as $function$
declare
pNOT_CODIGO ALIAS for $1;
REC   RECORD; 
vRETORNO NUMERIC;
vHISTORICOFINAL TEXT;
BEGIN
  vRETORNO:= 0;
FOR REC IN 
SELECT NF.ID AS NOTAFISCAL_ID, NF.NOT_NUMERO AS vNUMERONOTA, 
NF.NOT_PARCELA AS vPARCELANOTA,NF.NOT_EMPRESA AS vEMPRESANOTA, I.ID AS INTELIGENT_ID, I.HISTORICOFINAL as vHISTORICOFINAL, I.TIPO_VALOR as vTIPOVALOR
    FROM ${schema}.INTELIGENT I INNER JOIN
    ${schema}.COMPROVANTE C ON I.COMPROVANTE_ID = C.ID
    INNER JOIN ${schema}.NOTAFISCAL NF ON C.COM_CNPJ = NF.NOT_CNPJ
    WHERE I.ASSOCIADO = FALSE 
    AND C.COM_VALORDOCUMENTO = NF.NOT_VALORPARCELA
    AND C.COM_DATAVENCIMENTO = NF.NOT_DATAPARCELA
    AND C.TIPO_COMPROVANTE = 'TITULO'
    AND NF.ID = pNOT_CODIGO

 LOOP
 	IF (REC.vTIPOVALOR = 'PRINCIPAL') THEN
    vHISTORICOFINAL   := 'Pagto. NFe '|| REC.vNUMERONOTA || '/' || REC.vPARCELANOTA || ' de ' || REC.vEMPRESANOTA;
    ELSE
    vHISTORICOFINAL := REC.vHISTORICOFINAL || ' NFe '|| REC.vNUMERONOTA || '/' || REC.vPARCELANOTA || ' de ' || REC.vEMPRESANOTA;
    END IF;
   	update ${schema}.INTELIGENT set historicofinal = vHISTORICOFINAL, notafiscal_id = REC.NOTAFISCAL_ID where id = REC.INTELIGENT_ID;   	
	vRETORNO:= vRETORNO + 1;
 END LOOP; 
	if (vRETORNO > 0) THEN
	update ${schema}.notafiscal set processado = true where ID = pNOT_CODIGO;
	end if;
RETURN COALESCE(vRETORNO ,0);
END;
$function$;