CREATE OR REPLACE FUNCTION ${schema}.processa_notafiscalgeral("pPAR_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
  pPAR_CODIGO ALIAS FOR $1;  
  
  vCODIGONOTA NUMERIC;
  vRETORNO NUMERIC;
  vQUANTIDADE NUMERIC;
  
  cEXTRATOBANCARIO CURSOR FOR
  SELECT ID
  FROM ${schema}.NOTAFISCAL  
  WHERE  TNO_CODIGO=0
    AND PARCEIRO_ID= pPAR_CODIGO
    AND PROCESSADO= FALSE;  

BEGIN
 
  vRETORNO:= 0;
  
  OPEN cEXTRATOBANCARIO;
  LOOP
  FETCH cEXTRATOBANCARIO INTO vCODIGONOTA  ;
  EXIT WHEN NOT FOUND;
   SELECT ${schema}.PROCESSA_NOTAFISCALBB(CAST(vCODIGONOTA AS int8)) INTO vQUANTIDADE;
   IF vQUANTIDADE = 1 THEN
   UPDATE ${schema}.NOTAFISCAL SET PROCESSADO = TRUE WHERE ID = vCODIGONOTA;
   END IF;
   vRETORNO:= vRETORNO + vQUANTIDADE; 
  END LOOP;
  CLOSE cEXTRATOBANCARIO;
  RETURN COALESCE(vRETORNO ,0);

END;
$function$
;
