CREATE OR REPLACE FUNCTION ds_demo.processa_notafiscalgeral("pPAR_CODIGO" bigint, "pDATA_INICIAL" date)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
declare
  pPAR_CODIGO ALIAS for $1;
 pDATA_INICIAL ALIAS for $2;
  vRETORNO NUMERIC;
  vQUANTIDADE NUMERIC;
  vNOTAFISCAL_ID numeric;
  cNOTAGERAL CURSOR for SELECT id  FROM ds_demo.NOTAFISCAL  WHERE  TNO_CODIGO=0
    AND PARCEIRO_ID = CAST(pPAR_CODIGO AS int8) AND PROCESSADO = false and NOT_DATAPARCELA > cast(pDATA_INICIAL as DATE);
BEGIN 
  vRETORNO:= 0;  
  open cNOTAGERAL;
 loop
  FETCH cNOTAGERAL INTO vNOTAFISCAL_ID;
  EXIT WHEN NOT FOUND;
   SELECT * from ds_demo.processa_notafiscal(cast(vNOTAFISCAL_ID as INT8)) INTO vQUANTIDADE;
   vRETORNO:= vRETORNO + vQUANTIDADE; 
  END LOOP;
 close cNOTAGERAL;
  RETURN COALESCE(vRETORNO ,0);
END;
$function$
;
