CREATE OR REPLACE FUNCTION ds_demo.processa_notafiscal_semdata("pNOT_CODIGO" bigint)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
declare
pNOT_CODIGO ALIAS for $1;
REC   RECORD; 
vRETORNO NUMERIC;
vHISTORICOFINAL TEXT;
BEGIN
  vRETORNO:= 0;
FOR REC IN 
SELECT NF.ID AS NOTAFISCAL_ID, NF.NOT_NUMERO AS vNUMERONOTA, 
NF.NOT_PARCELA AS vPARCELANOTA,NF.NOT_EMPRESA AS vEMPRESANOTA, I.ID AS INTELIGENT_ID, I.HISTORICOFINAL as vHISTORICOFINAL, I.TIPO_VALOR as vTIPOVALOR
    FROM ds_demo.INTELIGENT I INNER JOIN
    ds_demo.COMPROVANTE C ON I.COMPROVANTE_ID = C.ID
    , ds_demo.NOTAFISCAL NF 
    WHERE I.ASSOCIADO = false
    and (C.COM_CNPJ = NF.NOT_CNPJ or substring(C.COM_CNPJ,1,8) = substring(NF.NOT_CNPJ,1,8))
    and NF.NOT_VALORPARCELA+10 >= C.COM_VALORDOCUMENTO
    and NF.NOT_VALORPARCELA <= C.COM_VALORDOCUMENTO
    AND C.TIPO_COMPROVANTE = 'TITULO'
    and NF.tno_codigo =0
    AND NF.ID = pNOT_CODIGO

 LOOP
 	IF (REC.vTIPOVALOR = 'PRINCIPAL') THEN
    vHISTORICOFINAL   := 'Pagto. NFe '|| REC.vNUMERONOTA || '/' || REC.vPARCELANOTA || ' de ' || REC.vEMPRESANOTA;
    ELSE
    vHISTORICOFINAL := REC.vHISTORICOFINAL || ' NFe '|| REC.vNUMERONOTA || '/' || REC.vPARCELANOTA || ' de ' || REC.vEMPRESANOTA;
    END IF;
   	update ds_demo.INTELIGENT set historicofinal = vHISTORICOFINAL, notafiscal_id = REC.NOTAFISCAL_ID where id = REC.INTELIGENT_ID;   	
	vRETORNO:= vRETORNO + 1;
 END LOOP; 
	if (vRETORNO > 0) THEN
	update ds_demo.notafiscal set processado = true where ID = pNOT_CODIGO;
	end if;
RETURN COALESCE(vRETORNO ,0);
END;
$function$
;
