CREATE OR REPLACE FUNCTION ${schema}.regra_function("parceiroId" bigint, "pPeriodo" character varying)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
  pParceiroId ALIAS FOR $1;  
  pPeriodo ALIAS FOR $2; 
  vRETORNO NUMERIC;
  REC_REGRA RECORD;
  REC_INTELIGENT RECORD;
  
BEGIN
vRETORNO := 0;	
	FOR REC_REGRA IN 
		SELECT * FROM ${schema}.REGRA WHERE PARCEIRO_ID = pParceiroId
	LOOP		
	  FOR REC_INTELIGENT IN
		SELECT i.* FROM ${schema}.INTELIGENT i inner join ${schema}.extrato e on i.extrato_id = e.id WHERE i.PARCEIRO_ID = pParceiroId AND i.PERIODO = pPeriodo and i.associado = false AND ((i.historico = REC_REGRA.REG_DESCRICAO AND REC_REGRA.TIPO_REGRA = 'HISTORICO')
		OR (e.info_adicional = REC_REGRA.REG_DESCRICAO AND REC_REGRA.TIPO_REGRA = 'INFORMACAO_ADICIONAL') OR (i.BENEFICIARIO = REC_REGRA.REG_DESCRICAO AND REC_REGRA.TIPO_REGRA = 'BENEFICIARIO'))
	  LOOP
	  UPDATE ${schema}.INTELIGENT SET CONTA_ID = REC_REGRA.CONTA_ID, HISTORICOFINAL = REC_REGRA.REG_HISTORICO, REGRA_ID = REC_REGRA.ID, ASSOCIADO = TRUE
	  WHERE ID = REC_INTELIGENT.ID;
	  vRETORNO := vRETORNO +1;
	  END LOOP;	
	END LOOP;
return vRETORNO;
END;
$function$
;
